name: Gradle Build and Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Gradle Test
      uses: MrRamych/gradle-actions/openjdk-12@3.1
      with:
        args: test
